language: python
os:
  - linux
python:
  - 2.7
services:
  - docker
before_install:
  - docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=database mysql:5.6
install:
  - make
  - make install
script:
  - make test
  - rest create user
  - cd user
  - rest migrate