language: python
os:
  - linux
python:
  - 2.7
services:
  - mysql
before_script:
  - mysql -e 'create database database;'"
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
install:
  - make
  - make install
script:
  - make test
  - rest create user
  - cd user
  - rest migrate