sudo: required
language: php
os:
  - linux
python:
  - 2.7
php:
  - 7.2
cache:
  directories:
    - $HOME/.composer
services:
  - mysql
before_script:
  - mysql -e 'create database `database`;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
install:
  - make
  - sudo make install
script:
  - make test
